-- Enable Row Level Security (RLS) is implied by creating policies, but good to be explicit
-- 1. Create Tables

-- Sheets (Folders/Notes)
create table public.sheets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  title text not null default 'Untitled',
  content text default '',
  color text default '#d8b4fe',
  target_date date,
  group_id text, -- For grouping versions or history if needed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tasks (To-Do items)
create table public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  sheet_id bigint references public.sheets(id) on delete cascade, -- Can be null for "Daily" tasks
  content text not null,
  is_done boolean default false,
  target_date date default current_date,
  reminder_at timestamp with time zone, -- New: For time-based reminders
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tags (Categories) - Optional Feature
create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  color text default '#64748b',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.task_tags (
  task_id bigint references public.tasks(id) on delete cascade,
  tag_id bigint references public.tags(id) on delete cascade,
  primary key (task_id, tag_id)
);

-- 2. Enable RLS
alter table public.sheets enable row level security;
alter table public.tasks enable row level security;
alter table public.tags enable row level security;
alter table public.task_tags enable row level security;

-- 3. Create Policies

-- Sheets Policies
create policy "Users can view their own sheets"
  on public.sheets for select
  using (auth.uid() = user_id);

create policy "Users can create their own sheets"
  on public.sheets for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own sheets"
  on public.sheets for update
  using (auth.uid() = user_id);

create policy "Users can delete their own sheets"
  on public.sheets for delete
  using (auth.uid() = user_id);

-- Tasks Policies
create policy "Users can view their own tasks"
  on public.tasks for select
  using (auth.uid() = user_id);

create policy "Users can create their own tasks"
  on public.tasks for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own tasks"
  on public.tasks for update
  using (auth.uid() = user_id);

create policy "Users can delete their own tasks"
  on public.tasks for delete
  using (auth.uid() = user_id);

-- Tags Policies
create policy "Users can view their own tags"
  on public.tags for select
  using (auth.uid() = user_id);

create policy "Users can create their own tags"
  on public.tags for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own tags"
  on public.tags for update
  using (auth.uid() = user_id);

create policy "Users can delete their own tags"
  on public.tags for delete
  using (auth.uid() = user_id);

-- Task Tags Policies (Junction table)
create policy "Users can view their own task tags"
  on public.task_tags for select
  using (
    exists ( select 1 from public.tasks where id = task_tags.task_id and user_id = auth.uid() )
  );

create policy "Users can create their own task tags"
  on public.task_tags for insert
  with check (
    exists ( select 1 from public.tasks where id = task_tags.task_id and user_id = auth.uid() )
  );

create policy "Users can delete their own task tags"
  on public.task_tags for delete
  using (
    exists ( select 1 from public.tasks where id = task_tags.task_id and user_id = auth.uid() )
  );
