-- Run this file to update your existing database with new features

-- 1. Add reminder support to existing tasks table
alter table public.tasks 
add column if not exists reminder_at timestamp with time zone;

-- 2. Create Tags Tables (if they don't exist yet)
create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  color text default '#64748b',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.task_tags (
  task_id bigint references public.tasks(id) on delete cascade,
  tag_id bigint references public.tags(id) on delete cascade,
  primary key (task_id, tag_id)
);

-- 3. Enable RLS for new tables
alter table public.tags enable row level security;
alter table public.task_tags enable row level security;

-- 4. Add Policies for Tags

-- Tags Policies
do $$ begin
  create policy "Users can view their own tags"
    on public.tags for select
    using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can create their own tags"
    on public.tags for insert
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can update their own tags"
    on public.tags for update
    using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can delete their own tags"
    on public.tags for delete
    using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

-- Task Tags Policies
do $$ begin
  create policy "Users can view their own task tags"
    on public.task_tags for select
    using (
      exists ( select 1 from public.tasks where id = task_tags.task_id and user_id = auth.uid() )
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can create their own task tags"
    on public.task_tags for insert
    with check (
      exists ( select 1 from public.tasks where id = task_tags.task_id and user_id = auth.uid() )
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can delete their own task tags"
    on public.task_tags for delete
    using (
      exists ( select 1 from public.tasks where id = task_tags.task_id and user_id = auth.uid() )
    );
exception when duplicate_object then null; end $$;
